### ISSUE TITLE
How to create an Entity with many attributes?

### ISSUE THREAD

**Issue by MortalFlesh** [cmeeren/Felicity#2]
Hello,
first of all, thanks for this library!

I'm trying to create a Resource, by operation.Post, but I'm not sure how to do it correctly.

There are just a couple of attributes in the example, I have 15 attributes at my Resource and the RequestParser can't handle all of them.

I've found it in the code here https://github.com/cmeeren/Felicity/blob/master/src/Felicity/RequestParser.fs#L474, it says 
`// TODO: Higher arities`

So is there any other way how to create a resource with that many attributes now?

---
What I have in mind is try to parse all attributes on my own in the Post function, and create a resource on my own. Then just pass the resource to the Parser, but I don't think it is a "correct" way to do it, since the parse won't do "parsing" in that case.

Also, I'm not sure how to use defined attributes in this way.

**Comment by cmeeren** [comment]
Hi! Does [this section in the docs](https://github.com/cmeeren/Felicity/blob/master/DOCUMENTATION.md#parsing-higher-arities-than-is-currently-available) answer your question? You can parse however many you want, it's just that you won't get the errors combined.

(By the way, the parsing may be changed to be simpler once F# supports the applicative `and!` keyword for CEs. Due to arrive in F# 5. That would allow combining errors for arbitrarily many parameters.)

**Comment by MortalFlesh** [comment]
Oh I missed this in the docs, this is exactly what I need! I wasn't sure how to use a `job` in my code.
Also this explains how `and!` will work 💡!

Thanks for quick reply.

**Comment by cmeeren** [comment]
No problem. There is also an `Async<Result<_,_>>` overload where you can use an `asyncResult` CE instead of `jobResult`, if you'd rather use that (so you don't need to use FsToolkit.ErrorHandling.JobResult).
